### ISSUE TITLE
about some error when running reactivity prediction module

### ISSUE THREAD

**Issue by Amanda233** [aspuru-guzik-group/Tartarus#1]

**Comment by Amanda233** [comment]
Hello! When I run reactivity prediction module.It have such typeError:
Traceback (most recent call last):
  File "/home/amanda/Tartarus/rec_ml_pre.py", line 10, in <module>
    Ea, Er, sum_Ea_Er, diff_Ea_Er = reactivity.get_properties(smi)
  File "/home/amanda/Tartarus/tartarus/reactivity.py", line 441, in get_properties
    sum_Ea_Er = activation_energy + reaction_energy if sa_score <= 6.0 else 10**4
TypeError: '<=' not supported between instances of 'NoneType' and 'float'

Do you have any idea how to solve this error?Is that because SA score is none?

**Comment by akshat998** [comment]
Hi Amanda, 

Thank you for pointing this out :) 

I was wondering which smile (variable smi) you were trying this for. It could definitely be because the sa_score is failing. Looking the smi will help me debug. 

Regards
Akshat

**Comment by gkwt** [comment]
Hello @Amanda233 ,

Thank you for reporting the issue. 

It is likely that the reactivity module is not installed correctly, so the simulation failed. We will add a print statement to make this error clearer. Please try the following with your smiles
```python
from tartarus import reactivity
result = reactivity.barrier_from_smiles(smiles)
```
and post your error message, if there is any.

Gary
