### ISSUE TITLE
Requesting reproducible code for GB-GA and REINVENT

### ISSUE THREAD

**Issue by hyeok9855** [aspuru-guzik-group/Tartarus#10]
Hello,

I'd like to replicate the experiments in your paper, but some codes are missing.
Could you upload a reproducible code for GB-GA and REINVENT that was presented in the original paper?
For REINVENT, I've checked the provided notebook file, but it does not work properly, maybe due to #9.

Thanks!

**Comment by akshat998** [comment]
Hi @hyeok9855,

The re-invent model code is available in the models directory and is set up as we used it in our experiments. You'll need to adjust the fitness functions to suit your specific benchmarks.

For the GB-GA model, I recommend checking out the original repository at https://github.com/jensengroup/GB_GA. We've adapted it by updating the initial dataset to one that's tailored for our needs and modifying the corresponding fitness function. You should find the code readily adaptable for your use. We plan to integrate our custom modifications into the main codebase in the future :) 

cc @gkwt 
Best regards,
Akshat

**Comment by hyeok9855** [comment]
Thank you for your response.

I'll dig more and let you know if any other issues arise!

Thanks!

**Comment by gkwt** [comment]
For future reference, the notebook for REINVENT in `models_jupyter` folder also contains a link to a repo `reinvent-benchmarking` for further details.
