### ISSUE TITLE
Dataset units

### ISSUE THREAD

**Issue by mhellstr** [aspuru-guzik-group/Tartarus#2]
What are the units for dipole moment, HOMO-LUMO gap, reaction energy, etc. ?

**Comment by akshat998** [comment]
Hello, 

The units are as follows: 
Dipole moment: D
HOMO-LUMO gap: eV
Reaction energy: kcal/mol

The tables in our paper might be able to help you further (the column descriptions have units) :) 

Regards
Akshat
